
#generated by ./configure
include autoconf/Makefile.config

OPAMDEPS=lwt ocp-build

all:
	$(MAKE) -C plugins/central_monitor
	$(MAKE) -C plugins/print_commands
	$(MAKE) ocaml

clean:
	$(MAKE) -C plugins/central_monitor clean
	$(MAKE) -C plugins/print_commands clean
	$(MAKE) ocaml-clean

ocaml:
	if [ ! -d "_obuild" ]; then ocp-build init; fi
	ocp-build

ocaml-clean:
	rm -rf _obuild

OCPBUILD=ocp-build
OCAMLOPT=ocamlopt.opt
OCAMLC=ocamlc
SRC=src

distclean: clean
	rm -f autoconf/config.log
	rm -f autoconf/Makefile.config
	rm -f autoconf/config.log
	rm -f autoconf/config.ocpgen
	rm -f autoconf/config.status
	rm -rf autoconf/autom4te.cache
	rm -rf _obuild/
	rm -f *~

opam-deps:
	opam install $(OPAMDEPS)

install:
	cp -f _obuild/ocp-show-build/ocp-show-build.asm $(BINDIR)/ocp-show-build
	cp -f plugins/central_monitor/central_monitor.so $(BINDIR)/
	cp -f plugins/print_commands/print_commands.so $(BINDIR)/
	ocp-build install ocplib-cplugin-monitor
